### ISSUE TITLE
Compare field limits between APIs and try to normalise

### ISSUE THREAD

**Issue by SimonDamberg** [SimonDamberg/app-theweathermen#11]

**Comment by theo8theo8** [comment]
timeStamp: same
lastUpdated ~same
airPressure: hPa
airTemperature: C
horizontalVisibility:km (possibly wa and owm  has max 10k)
windDirection: degree
windSpeed: SMHI-m/s, WA-km/h, OWM-m/s
windGustSpeed: as above
relativeHumidity: %
thunderProbability: only SMHI %
totalCloudCover: SMHI(0-8) wa/omw(%)
minPrecipitationIntensity: only SMHI mm
meanPrecipitationIntensity: mm
maxPrecipitationIntensity: only SMHI mm
precipitationCategory: only SMHI(0-8 cat) (others have in weathercat, can prob be parsed)
frozenPrecipitationFraction: only SMHI (-9, 0-100)
weatherSymbol: 0-19


uv: perhaps add, at least wa has, believe smhi has in other api
